# Generated by Django 3.2.3 on 2021-06-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('idnum', models.CharField(max_length=40, unique=True)),
                ('telnum', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
