# Generated by Django 3.2.3 on 2021-06-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='机场代码')),
                ('airport_name', models.CharField(max_length=20, unique=True, verbose_name='机场名称')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=20, verbose_name='航班号')),
                ('departure_day', models.DateField(verbose_name='出发日期')),
                ('departure_time', models.TimeField(verbose_name='出发时刻')),
                ('arrival_day', models.DateField(verbose_name='到达日期')),
                ('arrival_time', models.TimeField(verbose_name='到达时刻')),
                ('departure_airport', models.CharField(max_length=20, verbose_name='出发机场')),
                ('arrival_airport', models.CharField(max_length=20, verbose_name='到达机场')),
                ('stopover_airport', models.CharField(max_length=20, verbose_name='经停机场')),
                ('first_class_num', models.IntegerField(verbose_name='头等舱数')),
                ('first_class_price', models.IntegerField(verbose_name='头等舱价格')),
                ('economy_class_num', models.IntegerField(verbose_name='经济舱数')),
                ('economy_class_price', models.IntegerField(verbose_name='经济舱价格')),
                ('aircraft_type', models.CharField(blank=True, max_length=20, verbose_name='飞机型号')),
                ('voyage', models.IntegerField(blank='True', verbose_name='航程')),
                ('company', models.CharField(blank=True, max_length=40, verbose_name='航空公司')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20, verbose_name='账号')),
                ('flightnum', models.CharField(max_length=20, verbose_name='航班号')),
                ('departure_day', models.DateField(verbose_name='出发日期')),
                ('passid', models.CharField(max_length=20, verbose_name='乘机人身份证号')),
                ('classtype', models.CharField(max_length=20, verbose_name='舱位')),
                ('ordertime', models.DateTimeField(verbose_name='订票时间')),
            ],
        ),
        migrations.AlterField(
            model_name='passenger',
            name='idnum',
            field=models.CharField(max_length=20, verbose_name='乘机人身份证号'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=20, verbose_name='乘机人姓名'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='telnum',
            field=models.CharField(max_length=40, verbose_name='乘机人联系电话'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.ManyToManyField(to='app02.User', verbose_name='乘机人对应用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=40, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idnum',
            field=models.CharField(max_length=40, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telnum',
            field=models.CharField(max_length=20, unique=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=20, unique=True, verbose_name='账号'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['userid'], name='app02_order_userid_b53182_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_id', 'departure_day')},
        ),
    ]
